// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package v1

import (
	"backend/api/v1"
)

type ControllerCommon struct{}

func NewCommon() v1.IV1Common {
	return &ControllerCommon{}
}

type ControllerSystem struct{}

func NewSystem() v1.IV1System {
	return &ControllerSystem{}
}
