// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package device

import (
	"backend/api/device"
)

type ControllerV1 struct{}

func NewV1() device.IDeviceV1 {
	return &ControllerV1{}
}
