// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalRiseniotUserDao is internal type for wrapping internal DAO implements.
type internalRiseniotUserDao = *internal.RiseniotUserDao

// riseniotUserDao is the data access object for table riseniot_user.
// You can define custom methods on it to extend its functionality as you wish.
type riseniotUserDao struct {
	internalRiseniotUserDao
}

var (
	// RiseniotUser is globally public accessible object for table riseniot_user operations.
	RiseniotUser = riseniotUserDao{
		internal.NewRiseniotUserDao(),
	}
)

// Fill with you ideas below.
