// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSysDeviceStrategyDao is internal type for wrapping internal DAO implements.
type internalSysDeviceStrategyDao = *internal.SysDeviceStrategyDao

// sysDeviceStrategyDao is the data access object for table sys_device_strategy.
// You can define custom methods on it to extend its functionality as you wish.
type sysDeviceStrategyDao struct {
	internalSysDeviceStrategyDao
}

var (
	// SysDeviceStrategy is globally public accessible object for table sys_device_strategy operations.
	SysDeviceStrategy = sysDeviceStrategyDao{
		internal.NewSysDeviceStrategyDao(),
	}
)

// Fill with you ideas below.
