// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSysDeviceKindDao is internal type for wrapping internal DAO implements.
type internalSysDeviceKindDao = *internal.SysDeviceKindDao

// sysDeviceKindDao is the data access object for table sys_device_kind.
// You can define custom methods on it to extend its functionality as you wish.
type sysDeviceKindDao struct {
	internalSysDeviceKindDao
}

var (
	// SysDeviceKind is globally public accessible object for table sys_device_kind operations.
	SysDeviceKind = sysDeviceKindDao{
		internal.NewSysDeviceKindDao(),
	}
)

// Fill with you ideas below.
