// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSysDeviceStatusDao is internal type for wrapping internal DAO implements.
type internalSysDeviceStatusDao = *internal.SysDeviceStatusDao

// sysDeviceStatusDao is the data access object for table sys_device_status.
// You can define custom methods on it to extend its functionality as you wish.
type sysDeviceStatusDao struct {
	internalSysDeviceStatusDao
}

var (
	// SysDeviceStatus is globally public accessible object for table sys_device_status operations.
	SysDeviceStatus = sysDeviceStatusDao{
		internal.NewSysDeviceStatusDao(),
	}
)

// Fill with you ideas below.
