// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSysDeviceDao is internal type for wrapping internal DAO implements.
type internalSysDeviceDao = *internal.SysDeviceDao

// sysDeviceDao is the data access object for table sys_device.
// You can define custom methods on it to extend its functionality as you wish.
type sysDeviceDao struct {
	internalSysDeviceDao
}

var (
	// SysDevice is globally public accessible object for table sys_device operations.
	SysDevice = sysDeviceDao{
		internal.NewSysDeviceDao(),
	}
)

// Fill with you ideas below.
