// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalSysDeviceCategoryDataDao is internal type for wrapping internal DAO implements.
type internalSysDeviceCategoryDataDao = *internal.SysDeviceCategoryDataDao

// sysDeviceCategoryDataDao is the data access object for table sys_device_category_data.
// You can define custom methods on it to extend its functionality as you wish.
type sysDeviceCategoryDataDao struct {
	internalSysDeviceCategoryDataDao
}

var (
	// SysDeviceCategoryData is globally public accessible object for table sys_device_category_data operations.
	SysDeviceCategoryData = sysDeviceCategoryDataDao{
		internal.NewSysDeviceCategoryDataDao(),
	}
)

// Fill with you ideas below.
